<!DOCTYPE html>
<html>
  <!-- Mirrored from expovent-react.vercel.app/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 May 2024 16:02:56 GMT -->
  <!-- Added by HTTrack -->
  <meta
    http-equiv="content-type"
    content="text/html;charset=utf-8"
    />
  <!-- /Added by HTTrack -->
    <head>
        <meta charset="utf-8" />
        <link
            rel="stylesheet"
            data-href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;display=swap"
            data-optimized-fonts="true"
            />
        <link rel="icon" href="{{ URL::asset('build/media/favicon.png') }}" />
        <title>
            Landing Page - Event Management Dashboard React NextJs Template
        </title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex, follow" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
            />
        <link rel="icon" href="{{ URL::asset('build/media/favicon.png') }}" />
        <meta name="next-head-count" content="9" />
        <link
            rel="preload"
            href="{{ URL::asset('build/css/app.css') }}"
            as="style"
            />
        <link
            rel="stylesheet"
            href="{{ URL::asset('build/css/app.css') }}"
            data-n-g=""
            />
        <noscript data-n-css=""></noscript>

        <script src="{{ URL::asset('build/js/polyfills-0d1b80a048d4787e.js') }}"></script>
        <script src="{{ URL::asset('build/js/webpack-6afe86ff35db31cc.js') }}"></script>
        <script src="{{ URL::asset('build/js/framework-d51ece3d757c7ed2.js') }}"></script>
        <script src="{{ URL::asset('build/js/main-81bb36a6aee6d986.js') }}"></script>
        <script src="{{ URL::asset('build/js/_app-d4ec09ba86fa23b5.js') }}"></script>
        <script src="{{ URL::asset('build/js/4607-44de2254aebe5f39.js') }}"></script>
        <script src="{{ URL::asset('build/js/1239-12e8f239e1957a1b.js') }}"></script>
        <script src="{{ URL::asset('build/js/7142-66de4c62f6d97743.js') }}"></script>
        <script src="{{ URL::asset('build/js/8529-4b69ae82a6f4878e.js') }}"></script>
        <script src="{{ URL::asset('build/js/index-338f7080ea9bc9b0.js') }}"></script>
        <script src="{{ URL::asset('build/js/_buildManifest.js') }}"></script>
        <script src="{{ URL::asset('build/js/_ssgManifest.js') }}"></script>
        <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;display=swap"
            />
    </head>
    <body>
        <div id="__next">
            <main class="body-area bd-theme-dark">
            <div class="fix">
                <div class="offcanvas__info">
                <div class="offcanvas__wrapper">
                    <div class="offcanvas__content">
                    <div
                        class="offcanvas__top mb-40 d-flex justify-content-between align-items-center"
                        >
                        <div class="offcanvas__logo">
                        <a href="index.html"
                            ><img
                            src="{{ URL::asset('build/media/logo-black.51edaff6.svg') }}"
                            alt="logo not found"
                            /></a>
                        </div>
                        <div class="offcanvas__close">
                        <button><i class="fal fa-times"></i></button>
                        </div>
                    </div>
                    <div class="offcanvas__search mb-25">
                        <form action="#">
                        <input
                            type="text"
                            placeholder="What are you searching for?"
                            /><button type="submit">
                        <i class="far fa-search"></i>
                        </button>
                        </form>
                    </div>
                    <div class="mobile-menu fix mb-40"></div>
                    <div class="offcanvas__contact mt-30 mb-20">
                        <h4>Contact Info</h4>
                        <ul>
                        <li class="d-flex align-items-center">
                            <div class="offcanvas__contact-icon mr-15">
                            <i class="fal fa-map-marker-alt"></i>
                            </div>
                            <div class="offcanvas__contact-text">
                            <a
                                href="https://www.google.com/maps/place/Dhaka/@23.7806207,90.3492859,12z/data=!3m1!4b1!4m5!3m4!1s0x3755b8b087026b81:0x8fa563bbdd5904c2!8m2!3d23.8104753!4d90.4119873"
                                >12/A, Mirnada City Tower, NYC</a
                                >
                            </div>
                        </li>
                        <li class="d-flex align-items-center">
                            <div class="offcanvas__contact-icon mr-15">
                            <i class="far fa-phone"></i>
                            </div>
                            <div class="offcanvas__contact-text">
                            <a href="tel:+088889797697">+088889797697</a>
                            </div>
                        </li>
                        <li class="d-flex align-items-center">
                            <div class="offcanvas__contact-icon mr-15">
                            <i class="fal fa-envelope"></i>
                            </div>
                            <div class="offcanvas__contact-text">
                            <a href="tel:+012-345-6789"
                                ><span class="mailto:support@mail.com"
                                >support@mail.com</span
                                ></a
                                >
                            </div>
                        </li>
                        </ul>
                    </div>
                    <div class="offcanvas__social">
                        <ul>
                        <li>
                            <a href="https://www.facebook.com/"
                            ><i class="fa-brands fa-facebook"></i
                            ></a>
                        </li>
                        <li>
                            <a href="https://twitter.com/"
                            ><i class="fa-brands fa-twitter"></i
                            ></a>
                        </li>
                        <li>
                            <a href="https://bd.linkedin.com/"
                            ><i class="fa-brands fa-linkedin"></i
                            ></a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/"
                            ><i class="fa-brands fa-youtube"></i
                            ></a>
                        </li>
                        </ul>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="offcanvas__overlay"></div>
            <div class="offcanvas__overlay-white"></div>
            

            <!-- header-section -->
            @include('layouts.frontend-header')

            @yield('body')

            @include('layouts.frontend-footer')
            
            <div class="bd-theme-settings-area transition-3">
                <div class="bd-theme-wrapper bd-theme-dark">
                <div class="bd-theme-header text-center">
                    <h4 class="bd-theme-header-title">Template Settings</h4>
                </div>
                <div class="bd-theme-toggle mb-20 d-block">
                    <label class="bd-theme-toggle-main" for="bd-theme-toggler"
                    ><span class="bd-theme-toggle-dark active"
                    ><i class="fa-light fa-moon"></i> Dark</span
                    ><input type="checkbox" id="bd-theme-toggler" checked="" /><i
                    class="bd-theme-toggle-slide"
                    ></i
                    ><span class="bd-theme-toggle-light"
                    ><i class="fa-light fa-sun-bright"></i> Light</span
                    ></label
                    >
                </div>
                <div class="bd-theme-settings">
                    <div class="bd-theme-settings-wrapper">
                    <div class="bd-theme-settings-open">
                        <button class="bd-theme-settings-open-btn">
                        <span class="bd-theme-settings-gear"
                        ><i class="fa-light fa-gear"></i></span
                        ><span class="bd-theme-settings-close"
                        ><i class="fa-regular fa-xmark"></i
                        ></span>
                        </button>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="progress-wrap active-progress">
                <button id="back_to_top" type="button" class="back-to-top-btn">
                <svg
                    class="progress-circle svg-content"
                    width="100%"
                    height="100%"
                    viewBox="-1 -1 102 102"
                    >
                    <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"></path>
                </svg>
                </button>
            </div>
            </main>
        </div>
        <script id="__NEXT_DATA__" type="application/json">
            {
            "props": { "pageProps": {} },
            "page": "/",
            "query": {},
            "buildId": "10tcLR4Z-1GmfDXmyRDs3",
            "nextExport": true,
            "autoExport": true,
            "isFallback": false,
            "scriptLoader": []
            }
        </script>
    </body>
  <!-- Mirrored from expovent-react.vercel.app/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 08 May 2024 16:03:10 GMT -->
</html>